#
# Copyright 2018-2023 Terracotta, Inc., a Software AG company.
# Copyright Super iPaaS Integration LLC, an IBM Company 2024
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# See shared code location for steps and parameters:
# https://dev.azure.com/TerracottaCI/_git/terracotta

resources:
  repositories:
    - repository: templates
      type: git
      name: terracotta/terracotta

jobs:
  - template: build-templates/maven-common.yml@templates
    parameters:
      jobName: Linux_Java_8
      timeoutInMinutes: 180
      options: -B -Djava.test.version=1.8
      mavenGoals: 'clean verify'
      fetchDepth: 0 # need unlimited for license plugin
  - template: build-templates/maven-common.yml@templates
    parameters:
      jobName: Linux_Java_11
      timeoutInMinutes: 180
      options: -B -Djava.test.version=1.11
      mavenGoals: 'clean verify'
      fetchDepth: 0 # need unlimited for license plugin
  - template: build-templates/maven-common.yml@templates
    parameters:
      jobName: Linux_Java_17
      timeoutInMinutes: 180
      options: -B -Djava.test.version=1.17
      mavenGoals: 'clean verify'
      fetchDepth: 0 # need unlimited for license plugin
  - template: build-templates/maven-common.yml@templates
    parameters:
      jobName: Windows_Java_8
      timeoutInMinutes: 180
      vmImage: 'windows-latest'
      options: -B -Djava.test.version=1.8
      mavenGoals: 'clean verify'
      fetchDepth: 0 # need unlimited for license plugin
  - template: build-templates/maven-common.yml@templates
    parameters:
      jobName: Windows_Java_11
      timeoutInMinutes: 180
      vmImage: 'windows-latest'
      options: -B -Djava.test.version=1.11
      mavenGoals: 'clean verify'
      fetchDepth: 0 # need unlimited for license plugin
  - template: build-templates/maven-common.yml@templates
    parameters:
      jobName: Windows_Java_17
      timeoutInMinutes: 180
      vmImage: 'windows-latest'
      options: -B -Djava.test.version=1.17
      mavenGoals: 'clean verify'
      fetchDepth: 0 # need unlimited for license plugin
